### ISSUE TITLE
上拉刷新在android和chrome浏览器第一次运行时有机率报错无法运行

### ISSUE THREAD

**Issue by assgod** [dcloudio/mui#112]
上拉刷新的timeout时间设为0，在android和chrome浏览器第一次运行时有机率出现这个报错.IOS无问题

报错：
![uprefresh2](https://cloud.githubusercontent.com/assets/6192722/9844680/d5615486-5af7-11e5-8b06-e1e2670b6282.png)

报错位置：this.pullPoket为undefined
![uprefresh](https://cloud.githubusercontent.com/assets/6192722/9844604/10645638-5af7-11e5-9ace-5e16c40c1f33.png)

代码：
```javascript
			var time = 0
			mui.os.ios && (time = 0)			
		    setTimeout(function () {
		    	mui('#pullrefresh').pullRefresh().refresh(true);
				mui('#pullrefresh').pullRefresh().pullupLoading();	
			}, time);	
```

**Comment by fxy060608** [comment]
将代码放入mui.ready内
