### ISSUE TITLE
微信上dialog没有样式

### ISSUE THREAD

**Issue by icyflash** [dcloudio/mui#140]
如图所示，警告消息框和对话消息框没有样式

![1203114351](https://cloud.githubusercontent.com/assets/578257/11552090/65a528ea-99bb-11e5-89ea-61983c165242.png)
![1203114416](https://cloud.githubusercontent.com/assets/578257/11552091/6a58d4ae-99bb-11e5-8302-f7a69cb175d9.png)

**Comment by hbcui1984** [comment]
确认有问题，会尽快升级

**Comment by hbcui1984** [comment]
http://www.dcloud.io/hellomui这个版本下的dialog已升级，变成统一UI的dialog（DIV自绘）；目前正式发布的mui，依然是系统浏览器默认的dialog。

**Comment by icyflash** [comment]
呃，http://www.dcloud.io/hellomui 和 Github 里面的不是一套么？

**Comment by 4013465w** [comment]
![tger](https://cloud.githubusercontent.com/assets/6347990/11553306/670515da-99c8-11e5-97b1-8995583eaceb.png)


这个demo也有点问题

**Comment by toaric** [comment]
能不能把github上的demo更新成和官网的一样呀。可以支持PC浏览

**Comment by YaoJingJing** [comment]
恩    希望能尽快更新

**Comment by hbcui1984** [comment]
最新版本已统一，支持PC端浏览，但mui目前未针对pc端做优化，特别是IE浏览器，因此暂时还不建议使用于PC端
