### ISSUE TITLE
预加载页面后,打开页面会卡顿

### ISSUE THREAD

**Issue by EasonZhang2015** [dcloudio/mui#148]
我使用了典型的"列表-详情"的结构。因为详情页是通用的，所以我在打开应用的时候就将详情页面用mui.proload()方法预加载。列表页面点击时，正常的效果是：被点击的dom块会有颜色加深跳转页面马上消失的效果。然而使用preload后，点击后颜色加深不会消失，当从详情页面点击后退的时候加深的效果还在，然后消失。感觉加深的效果被阻塞了一样，看起来有卡顿的效果。

**Comment by EasonZhang2015** [comment]
如果不使用预加载的话则没有任何问题，点击后加深跳转，跳转前加深的部分就已经还原了。注：这里的加深指的就是tap不放开的效果，正常放开后focus的加深效果会还原的。用preload还原的时间点被延迟到了打开一个页面，返回列表页后才执行了。体验上很不舒服。

**Comment by fxy060608** [comment]
该问题的产生是因为你的窗口切换动画是走截图的、预加载模式下因为很快触发了窗口切换、runtime截图当前webview时是高亮状态、导致打开、后退时的截图都是高亮未取消

**Comment by EasonZhang2015** [comment]
@fxy060608 那么只要使用预加载，这个问题就无法避免吗？

**Comment by fxy060608** [comment]
@EasonZhang2015 你可以试试延迟多少毫秒之后再show窗体

**Comment by EasonZhang2015** [comment]
@fxy060608 使用预加载就是为了节约这么几毫秒啊，不使用预加载就没这个问题了。那么这个问题确定是不修复了吗

**Comment by fxy060608** [comment]
@EasonZhang2015 不用pop-in动画，改用slide-in动画。

**Comment by EasonZhang2015** [comment]
@fxy060608 延迟试过了，没效果，多久还是截图。用pop-in是为了解决背景模糊的问题

**Comment by fxy060608** [comment]
@EasonZhang2015 你是说延迟show，即使在高亮已经消失之后再show，窗体切换动画仍会看到高亮状态？

**Comment by EasonZhang2015** [comment]
@fxy060608 刚才错误理解你说的延迟了，使用了show中的延迟。现在更改为执行show前20毫秒左右就可以了，为了保险起见我将延迟设置程了50毫秒。另外分享下延迟传参的代码：setTimeout(function(){openNew(这里传参数)},50);

**Comment by EasonZhang2015** [comment]
@fxy060608 感谢迅速的支持！

**Comment by EasonZhang2015** [comment]
@fxy060608 
又遇到了类似的问题。新窗口打开后也会停一下再渲染dom，是否也是动画造成的呢？
传送门：http://ask.dcloud.net.cn/question/14197

**Comment by fxy060608** [comment]
ajax回调结束后再show窗体

**Comment by EasonZhang2015** [comment]
@fxy060608 我是这么做的。现在改为ajax结束后mui.fire通知列表页显示详情页窗体。并且延迟50ms就可以了。所以这个问题也应该是截图造成的吧

**Comment by fxy060608** [comment]
嗯、pop-in动画执行时会截图两个窗体进行动画
