### ISSUE TITLE
瞬间点击多次会触发多次tap事件

### ISSUE THREAD

**Issue by EasonZhang2015** [dcloudio/mui#151]
多次点击多次触发tap事件，如果tap事件是打开webview会瞬间打开好几个webview。而且快速点击应该是并发的，自己加锁也无法限制住，这个bug大约什么时候能解决啊。

**Comment by Thyiad** [comment]
这算哪门子BUG

你自己点击后把这个元素设置为disabled啊，点击完后再设置回去不就得了

**Comment by EasonZhang2015** [comment]
http://ask.dcloud.net.cn/question/2226
参照去年DCloud_heavensoft的回复。
回答问题负点责任，至少自己尝试过。我说了快速点击可能是并发，disabled没生效前第二次tap就已经出发了。

**Comment by Thyiad** [comment]
我也碰到过，但是自己设置disabled就可以了。至于你说的并发，不清楚

**Comment by fxy060608** [comment]
@EasonZhang2015 你是怎么添加的锁逻辑，贴下代码

**Comment by EasonZhang2015** [comment]
因为我页面是预加载的，所以这里定时器延迟1秒解锁。但是不是每台手机上都有效，社区也有人遇到这个问题，所有怀疑是否是并发的。

// 设置锁的初始状态为关闭
var lock = false;

// 主列表点击事件
mui('#list').on('tap', 'a', function() {
	// 判断锁的状态
	if(lock){
		return;
	}
	// 打开锁
	lock = true;
	// 获取需要拉取数据的id
	var objId = this.getAttribute('data-id');
	// 获取到详情页面
	var page = plus.webview.getWebviewById('ratedetail.html');
	
	// 通知详情页面去ajax拉取数据(在渲染页面和移动窗体之前)
	mui.fire(page,'pulldata',{objId:objId});
	
	// 关闭锁
	setTimeout(function(){
		lock = false;
	},1000)
});

**Comment by fxy060608** [comment]
现在的代码，多次点击会打开多个webview？你在几个关键位置打下日志，比如刚进入tap里打印一下，lock的时候打印一下。timeout的时候打印一下。看看是哪个地方出现的问题

**Comment by EasonZhang2015** [comment]
@fxy060608 类似的情况，有什么比较通用的解决方案吗？

**Comment by fxy060608** [comment]
@EasonZhang2015 通用的就是加lock。比如在openWindow里边加。跟你的逻辑差不多

**Comment by EasonZhang2015** [comment]
@fxy060608 社区里heavensoft之前说会从框架层解决这个问题，目前这个还会排到近期的更新中去吗？主要考虑到加锁工作的话也要在每个tap事件上写相同的代码。

**Comment by fxy060608** [comment]
@EasonZhang2015 目前框架层面解决也只能解决openWindow里的。你这个是自己实现的。还是需要自己处理。

**Comment by EasonZhang2015** [comment]
@fxy060608 感谢及时回复
