### ISSUE TITLE
高德地图不能在mui上使用吗？

### ISSUE THREAD

**Issue by ZhenZinian** [dcloudio/mui#157]
用百度可以，用高德地图甚至无法通过getCurrentPosition() 获取到坐标

appkey设置正确，provider也设置成amap了。

**Comment by hbcui1984** [comment]
这个问题其实和mui无关，参考：http://ask.dcloud.net.cn/article/91 中“mui、HTML5+、5+Runtime的关系说明”章节；若依然有问题，可以在ask社区发帖提问。
