### ISSUE TITLE
关于安卓开发怎么 用pc 调试

### ISSUE THREAD

**Issue by VanquisherMe** [dcloudio/mui#158]
项目 打包后 难道 只能在 安卓手机调试 ，css 样式 ，和 请求的 json 怎么 调试  看到 ，其实 就是在 win10 下 怎么 调试

**Comment by chuilee** [comment]
Dcloud问答下有 http://ask.dcloud.net.cn/docs#http://ask.dcloud.net.cn/article/69

**Comment by hbcui1984** [comment]
如@chuilee 所说，参考ask社区文档，注意chrome调试需要翻墙
