### ISSUE TITLE
支持commonjs的引入方式吗？npm上有这个包吗？

### ISSUE THREAD

**Issue by p2227** [dcloudio/mui#164]
如题，简单地搜索了一下没有发现

**Comment by fxy060608** [comment]
暂未发布到npm，commonjs你可以自己exports一下即可。

**Comment by p2227** [comment]
里面用到 arguments.callee，ES6下不允许

**Comment by fxy060608** [comment]
你需要在ES6下编译，运行？

**Comment by p2227** [comment]
用webpack的话，就是严格模式的，我看看那边有没有配置项吧

**Comment by fxy060608** [comment]
你可以排查下是不是构建环境限制了或者代码里使用了use strict

**Comment by p2227** [comment]
use strict 是因为用了babel，排除掉就没事了

**Comment by AllenBird** [comment]
能不能npm发一把
