### ISSUE TITLE
使用webpack对mui.css进行打包混淆操作时报错

### ISSUE THREAD

**Issue by bigmeow** [dcloudio/mui#168]
使用webpack -p 命令进行压缩混淆时，会报错；之所有把问题提在这里，是因为经过多次测试，发现是mui.css的问题，无法对这个文件进行压缩混淆操作，我吧mui.css里面的代码换成我自己写的样式，或者换成其他第三方库比如bootstrap的样式，都可以顺利编译通过，所以可以推断出：mui.css的某些代码不支持？
下面是报错内容：
![image](https://cloud.githubusercontent.com/assets/10484248/13804516/b34c3dc6-eb88-11e5-8b1e-0ba14903b4e5.png)

**Comment by bigmeow** [comment]
问题解决了。。。中分法排除比对代码，是mui.css里面的  mui-spinner  这个class在作怪，background-url用的svg，删除掉就没事

**Comment by bigmeow** [comment]
根本原因找到了：
原代码是：
`.mui-spinner-white:after {
	background-image: url('data:image/svg+xml;charset=utf-8,<svg>中间省略1千字符串</svg>');
}
`
改过后的文件：
`
.mui-spinner-white:after {
	background-image: url("data:image/svg+xml;charset=utf-8,<svg>中间省略1千字符串</svg>");
}
`

总结：css里面的引号请使用双引号，手动滑稽

**Comment by synchronizingtheworld** [comment]
根本原因太棒了！我还说来把这个问题贴出来。
