### ISSUE TITLE
是否支持Linux平台？windows已删！如果使用Linux平台需要哪种开发工具？

### ISSUE THREAD

**Issue by JamesLiAndroid** [dcloudio/mui#174]

**Comment by hbcui1984** [comment]
你说的是HBuilder？HBuilder目前支持windows和mac两个版本，暂不支持linux。

**Comment by JamesLiAndroid** [comment]
@hbcui1984 我的意思是，在Linux下没有HBuilder，用其他工具可以吗？Sublime还是atom？
能否针对这些工具开发一下插件。我主要还是做原生开发，但是公司有混合开发的要求。

**Comment by WillinChang** [comment]
下载Android的本地打包版本即可使用 eclipse adt 或者 android studio （idea ） 开发。
http://ask.dcloud.net.cn/article/38
