### ISSUE TITLE
数字输入框的bug：会导致双倍step的增减

### ISSUE THREAD

**Issue by senntyou** [dcloudio/mui#179]
![image](https://cloud.githubusercontent.com/assets/12265053/14344427/19d1d72e-fcda-11e5-94df-a0bc259e905d.png)

bug场景：我的step是10，结果每次增减都是20.
原因分析：监听的事件有问题.
修复：https://github.com/dcloudio/mui/blob/master/js/mui.number.js#L11
把
```
var tapEventName = touchSupport ? 'tap' : 'click';
```
改成
```
var tapEventName = touchSupport ? 'touchend' : 'click';
```
就ok了.

**Comment by fxy060608** [comment]
排查是不是引用了两个mui或者第三方提供了tap事件的类库，如zepto的touch模块

**Comment by senntyou** [comment]
@fxy060608 
确实是这样，但是想要保留两者，只能采取一些折中的办法，修改一些事件。
谢谢你的解答！

**Comment by fxy060608** [comment]
如果是zepto可以不包含touch模块的
