### ISSUE TITLE
v3.0.0 mui.alert()文字过长时不会自动换行

### ISSUE THREAD

**Issue by jinghang** [dcloudio/mui#188]
最新版本v3.0.0出现这个问题，以前的版本没有。看了弹窗html源码，新版是把以前的
`<div class=mui-popu-text></div>`
换成了
`<pre class=mui-popu-text></pre>`，

![image](https://cloud.githubusercontent.com/assets/3844686/15106070/419cf472-15f9-11e6-99ee-7ac4220c0b8c.png)

我是加样式来解决这个问题
`<style>
        pre {white-space: pre-wrap;word-wrap: break-word;}
    </style>`

**Comment by fxy060608** [comment]
下个版本修复此问题，调整为pre是为了解决\n换行问题。下个版本会恢复为div。然后代码里替换\n换行符

**Comment by KavenSu** [comment]
期待尽快修复、

**Comment by hbcui1984** [comment]
mui v3.0.0 已实现：H5版本的dialog控件支持换行（\n）显示

**Comment by webScholl** [comment]
发生过的地方是感动   收到奥迪的颠倒是非的舒服舒服个梵蒂冈梵蒂冈复古风的鬼地方个地方是感动发生过的时光
