### ISSUE TITLE
摇一摇能增加个摇完的返回值吗

### ISSUE THREAD

**Issue by qinzhongjie** [dcloudio/mui#197]
摇一摇功能摇完怎么显示出结果，比如摇完弹出HelloWorld，折腾了几天了，还是没有实现，求官方指导啊。。

**Comment by hbcui1984** [comment]
这是HTML5 PLUS的功能，建议在[http://ask.dcloud.net.cn/explore/category-1](http://ask.dcloud.net.cn/explore/category-1)发起提问。

**Comment by qinzhongjie** [comment]
好的 ，收到！
