### ISSUE TITLE
能否增加Card/Panel组件

### ISSUE THREAD

**Issue by ragnaroks** [dcloudio/mui#203]
由于目前开发的是一个只针对于平板的项目,需要一些块状排列的区域来显示文本
![image](https://cloud.githubusercontent.com/assets/7598199/15561504/28472e1a-2329-11e6-94aa-8e527eca1241.png)
![image](https://cloud.githubusercontent.com/assets/7598199/15561524/741d3384-2329-11e6-81c0-93c7b3fbebbb.png)

**Comment by hbcui1984** [comment]
这个倒是在需求列表中，应该很快会提供
