### ISSUE TITLE
tab-webview-main 页面异常

### ISSUE THREAD

**Issue by a284628487** [dcloudio/mui#204]
tab-webview-main.html，tab选项卡webview模式，子页面显示不出来，tab能正常切换，
跟踪到 plus.webview.show(targetTab,"fade-in",300); plus是空的.

**Comment by hbcui1984** [comment]
确认是在手机真机上运行的？建议参考：http://ask.dcloud.net.cn/article/165

**Comment by a284628487** [comment]
在真机上运行成功了，但有个疑问，是否tab选项卡的webview模式只能在打包成apk或者ipa之后才能正常运行，而不能直接把页面文件放在某个服务器上，通过其它浏览器来加载？

**Comment by hbcui1984** [comment]
是的，webview模式的选项卡，必须打包成apk或ipa，在普通手机浏览器上无法使用；此时可以考虑div模式的选项卡

**Comment by a284628487** [comment]
非常感谢!
