### ISSUE TITLE
升级过后plus.nativeUI.actionsheet样式异常

### ISSUE THREAD

**Issue by wujunchuan** [dcloudio/mui#251]
Hbuilder升级过后，使用plus.nativeUI.actionsheet的样式就变了
![image](https://cloud.githubusercontent.com/assets/7511631/19162753/be3c630c-8c2b-11e6-9adf-7a05ddcd8127.png)

**Comment by qhhsy** [comment]
此问题已解决,下个正式版修复,目前可以使用alpha  HBuilder
[http://ask.dcloud.net.cn/article/900](url)
