### ISSUE TITLE
手册烂的一塌糊涂，提问也没人回答，同意的回复个1。

### ISSUE THREAD

**Issue by Megasu** [dcloudio/mui#265]
这个 MUI 项目就像一个被遗弃的项目。
是不是因为之前MUI的负责人升官或跳槽了，留下这个烂摊子没人管，能不能找专人重构或者维护更新。
尤其是手册，是我见过最烂的框架手册了，能不能参考其他框架手册搞一份新的MUI手册。
国内MUI其实做的还可以，多少人因为MUI手册反人类，转而用了其他手册做的用心框架。
同意：“手册烂的一塌糊涂，提问也没人回答”这个观点的回复个1，看看负责人会在多少个月后才出现。

**Comment by Megasu** [comment]
1

**Comment by Megasu** [comment]
MUI项目负责人：hbcui1984
GitHub地址：https://github.com/hbcui1984
一年365天，hbcui1984 今年在GitHub就登录了46次而已，可见MUI负责人对这个项目的态度。
自己太忙没时间不维护可以理解，但可以安排其他人维护重构，不然白白浪费了MUI这个名字。
希望MUI负责人对粉丝或使用MUI的开发者更负责任些。
至少安排个同事把这个两三年前的反人类手册更新一下，做成更方便开发者使用的手册。

**Comment by xuzili1993** [comment]
1

**Comment by zhouAndy** [comment]
是很烂~手册的可读性真的很差~

**Comment by zhe-he** [comment]
都是程序员，看看源码吧 /偷笑

**Comment by airyland** [comment]
MUI 应该是 Dcloud 的项目，但是连 Dcloud 感觉都没更新了。官网产品还是 n 久前的样子, 甚至还挂着和 apicloud 撕逼的公告。

**Comment by qhhsy** [comment]
@Megasu 您的问题在群里面回复过您,MUI  基础框架已经趋于成熟,已经过了疯狂修补Bug的阶段.现在更多的是再补充组件.你觉得"MUI手册反人类" 在哪里呢? 欢迎提建议.不够完善清晰? 还是写的杂乱,搜索不到?

**Comment by wjJSBlog** [comment]
1111111

**Comment by stormwy** [comment]
@qhhsy demo里面有一些地方的api的使用没有在文档中体现。
比如在http://www.dcloud.io/hellomui/examples/setting.html这个demo里,mui('#app').view(option)这个方法在文档里面是找不到的。

**Comment by yhsy** [comment]
1

**Comment by udbmnm** [comment]
2

**Comment by tiandao-dongguan** [comment]
1

**Comment by tiandao-dongguan** [comment]
说实话，广告打的很好，但是。。。。
1.文档差劲，看了老半天才知道，这mui不能完全适配wap站。
2.示例很少，问答也无人响应。
3.无教学视频，官方宣称自己没时间做。首页都是别的培训机构的视频。
4.没几个全面的模板来可以参考的。

**Comment by rccoder** [comment]
@Megasu @tiandao-dongguan 

自己能力差还瞎 BB 啥，人家没强迫你用

企业是赚钱的，扔掉东西又有什么不可以？

**Comment by tiandao-dongguan** [comment]
@rccoder 脑残粉太可怕，比喷子还可怕。

**Comment by MetSystem** [comment]
1

**Comment by wtujvk** [comment]
demo太少，文档不够清晰，不会使用...

**Comment by LastQuarterMoon** [comment]
1

**Comment by Sunsongoing** [comment]
手册告诉基本用法就行了，不过论坛动不动就让去看手册是在玩我吗？ 我要是看手册能解决问题还来提问干嘛

**Comment by lslcoded** [comment]
1

**Comment by lslcoded** [comment]
1

**Comment by lslcoded** [comment]
1

**Comment by lslcoded** [comment]
1

**Comment by lslcoded** [comment]
1

**Comment by wzc0x0** [comment]
1

**Comment by wzc0x0** [comment]
其实还是不错的，不好好搞就没办法了

**Comment by wwb568109135** [comment]
1，对小白不友好！

**Comment by yinruifang1993** [comment]
1

**Comment by yinruifang1993** [comment]
1,对于初学者来着，真的是不太友好

**Comment by lv23ji** [comment]
真的差哦 手册

**Comment by yoyo837** [comment]
这issue都看了几个月，我也来说一句。
如果没有良好的HTML+CSS+JS基础，使用MUI，感觉手册、文档不友好，正常。
反之，有良好基础的话，如果觉得文档还是不好用，建议提一些实际性的问题。提问没有人回答是途径、社区和生态活跃程度等相关的，开源作者理论上没有义务。

**Comment by aov2005** [comment]
开源本来就是希望大家一起维护，整天等着饭来张口的日子还嫌这嫌那的，u can u up？
