### ISSUE TITLE
求开放js模块化的目录

### ISSUE THREAD

**Issue by zhe-he** [dcloudio/mui#266]
没有找到mui项目中的js中单个的模块，只找到了合并后的，没压缩有100多KB。
css 没压缩也有100KB了

**Comment by hbcui1984** [comment]
这个早就开源了，https://github.com/dcloudio/mui/tree/master/js 目录下为模块js，https://github.com/dcloudio/mui/tree/master/sass 为模块sass文件，自己修改根目录下的Gruntfile.js，即可根据需求定制编译

**Comment by zhe-he** [comment]
thanks!
