### ISSUE TITLE
slider初始化后先使用切换问题

### ISSUE THREAD

**Issue by yoyo837** [dcloudio/mui#271]
当slider初始化后没有touch滑动操作，先使用api调用prevItem、nextItem时，mui-slider-group的translate3d的x只挪动-100px，一旦touch滑动操作后，再调用这两个api就是正常的了。

v2.9.0

**Comment by fxy060608** [comment]
初始化的时候该slider是否已完全显示了？移动距离是跟元素大小相关的、如果元素处于不可见时可能计算错误、而每次touch时会重新校验一下、所以又变正常了

**Comment by yoyo837** [comment]
@fxy060608 确实是这个原因的问题
