### ISSUE TITLE
文档说明为什么不全

### ISSUE THREAD

**Issue by Chasen-Zhang** [dcloudio/mui#278]
mui.init({
  pullRefresh : {
    container:refreshContainer,//待刷新区域标识，querySelector能定位的css选择器均可，比如：id、.class等
    up : {
      height:50,//可选.默认50.触发上拉加载拖动距离
      auto:true,//可选,默认false.自动上拉加载一次
      contentrefresh : "正在加载...",//可选，正在加载状态时，上拉加载控件上显示的标题内容
      contentnomore:'没有更多数据了',//可选，请求完毕若没有更多数据时显示的提醒内容；
      callback :pullfresh-function //必选，刷新函数，根据具体业务来编写，比如通过ajax从服务器获取新数据；
    }
  }
});

比如说pullRefresh 对象里具体有哪些配置项，没有文档可查？这个应该解决一下吧

**Comment by qhhsy** [comment]
请参考文档.http://dev.dcloud.net.cn/mui/pulldown/

**Comment by Chasen-Zhang** [comment]
但是这里面不全
