### ISSUE TITLE
长页面，alert弹框不在屏幕中间

### ISSUE THREAD

**Issue by zhangxiaozhou** [dcloudio/mui#317]
做了一个长页面，大概两屏的样子，然后底部按钮，alert的时候，弹框看不到，要拉到屏幕上部才看到弹框

**Comment by nearwmy** [comment]
你好，测试在长页面中mui.alert() 和原生alert()的弹窗位置都没有问题，都是调用的原生alert弹窗，能具体描述下你是在哪里用到的 最好能上传个能复现的demo

**Comment by zhangxiaozhou** [comment]
问题解决了，是因为我的hbuilder版本太低了，引入的mui版本太低有这个问题，后来换了HBuilder高版本解决了。
