### ISSUE TITLE
mui顶部的状态栏颜色怎么修改呢

### ISSUE THREAD

**Issue by zhangvivian** [dcloudio/mui#330]
有示例吗，各位大神

**Comment by niugaohang** [comment]
<script type="text/javascript" charset="utf-8">
      	mui.init(
      		// 设置系统状态栏背景色 和字体颜色
        		plus.navigator.setStatusBarBackground("#1E90FF"),
        		plus.navigator.setStatusBarStyle( "UIStatusBarStyleBlackOpaque" )
      	)
   </script>
放在head里

**Comment by hbcui1984** [comment]
参考：http://ask.dcloud.net.cn/article/1150
