### ISSUE TITLE
强烈建议官方把API文档梳理一下！！！

### ISSUE THREAD

**Issue by JacBian** [dcloudio/mui#335]
本菜鸟以前用过apicloud做混合开发，最近新项目改用mui平台，就开始看mui的demo，单单一个登录demo的代码，我发现很多代码写法和全局性对象比如plus，找遍了官方的API都没看到....
       不知道MUI团队的人有没有看过apicloud官方的文档，核心api对象的文档和第三方SDK，还有布局，样式这些清晰的分开，有整体的目录，我觉得那才是人看的文档。

**Comment by chenhaoxiang** [comment]
赞同

**Comment by leonlam** [comment]
强烈赞同。

**Comment by leonlam** [comment]
好项目就该健康地发展下去

**Comment by udbmnm** [comment]
虽然api*** shit但是他们文档的用户体验确实好些

**Comment by zhaomenghuan** [comment]
先看看这里的文档：[html5plus](http://www.html5plus.org/doc/h5p.html) 和 [mui](http://dev.dcloud.net.cn/mui/ui/)
了解了html5+ 、mui的联系与区别，剩下的就简单了。可以看看这里的demo：https://github.com/zhaomenghuan/mui-demo。

**Comment by furylee** [comment]
页面传值自己都弃用了,但是文档还不更新,我弄半天没弄明白,原来弃用了都

**Comment by Jack-93** [comment]
唉，MUI自己害死自己，感觉MUI其实可玩性比apicloud更高，可惜啊
