### ISSUE TITLE
关于对mui的借鉴，征询一下作者意见

### ISSUE THREAD

**Issue by ShanaMaid** [dcloudio/mui#351]
作者您好，首先感谢您和其它开源开发者对于mui的贡献，这是一套非常棒的组件库。
我计划做一套移动端的vue组件库，起始的基础组件将全部参照mui，css部分将会直接复用mui的样式并进行一些修改。关于这一点我希望征得您的同意，我将会在项目中声明对mui的借鉴。不知道您意下如何？
最后，再次感谢您的辛勤付出！

**Comment by hbcui1984** [comment]
MUI遵循MIT协议，这是一个比较宽松的协议，在此协议范围之内的，你可以随意使用
