### ISSUE TITLE
运行 [列表到详情最佳实践] 报错

### ISSUE THREAD

**Issue by whilenojava** [dcloudio/mui#370]
[Web浏览器] "Uncaught TypeError: Cannot read property 'addEventListener' of undefined"	/mui-master/examples/hello-mui/js/mui.min.js (7)

**Comment by lanxkk** [comment]
MUI官方工作人员的回复是：列表到详情最佳实践，是在App环境下运行的，因为涉及预加载、多webview通讯等，不适合浏览器环境下运行。

原文请见这个页面的评论区：http://ask.dcloud.net.cn/article/12575
