### ISSUE TITLE
8.8.5严重问题，nativetTab一碰到map就白屏

### ISSUE THREAD

**Issue by he426100** [dcloudio/mui#373]
用mui examples下的nativeTab测的，只要在index.html加var a = new plus.maps.Map("allmap");从其他tab切换到首页后首页就会白屏

![4k 1xq 9 sm80 i1 v6](https://user-images.githubusercontent.com/9689137/32328385-cb313ae2-c014-11e7-8522-873e3bff7083.png)
![Uploading ([@U{QEN2L}U~4A]62P_)GA.png…]()

**Comment by he426100** [comment]
@hbcui1984   @jinwei233  @fxy060608  @fudiandong  @seamanjiang

**Comment by nearwmy** [comment]
https://ask.dcloud.net.cn/question/49185 此贴已经回复
