### ISSUE TITLE
官方MUI例子中tab-top-webview中，首次滑动会出现遮挡顶部情况，具体如图

### ISSUE THREAD

**Issue by YaoYuebing** [dcloudio/mui#375]
![qq 20171107002053](https://user-images.githubusercontent.com/18578696/32451384-9cbb1058-c351-11e7-9540-f69e1dfac0f3.jpg)
![qq 20171107002049](https://user-images.githubusercontent.com/18578696/32451385-9ce8aac2-c351-11e7-924b-c31380c9443f.jpg)

测试手机小米4，只有首次滑动会出现这种情况

**Comment by wanggangdiao** [comment]
同问，希望官方尽快解决，谢谢！

**Comment by YaoYuebing** [comment]
@wanggangdiao @hbcui1984 @ @jinwei233 @fxy060608 @fudiandong

**Comment by hbcui1984** [comment]
该问题已修复，参考https://github.com/dcloudio/mui/commit/995d5b8110e2454eb4c28d0d5a3cb5120b656fe5
