### ISSUE TITLE
Demo 出现Cannot read property 'show' of undefined(…)

### ISSUE THREAD

**Issue by Joker1995** [dcloudio/mui#379]
offcanvas-drag-right-plus-main.html:126 Uncaught TypeError: Cannot read property 'show' of undefined(…)

**Comment by nearwmy** [comment]
这个html需要在plus环境下执行，浏览器运行会报错的。

**Comment by Joker1995** [comment]
今天才知道的plus环境和浏览器环境不一样,谢谢
