### ISSUE TITLE
IOS图片无法显示安卓显示正常

### ISSUE THREAD

**Issue by dh13899396662** [dcloudio/mui#383]
1.同一个url获取的头像,安卓显示正常,ios无法显示,
2.换本地的图片,ios就能显示正常.
求大神指点

**Comment by hbcui1984** [comment]
最好有可重现问题的示例

**Comment by dh13899396662** [comment]
![default](https://user-images.githubusercontent.com/32675044/33862544-35422e50-df1e-11e7-96aa-e7c8fd0420f3.jpg)
先在这谢谢您了。
![ios](https://user-images.githubusercontent.com/32675044/33862536-2bcc694e-df1e-11e7-8f25-057b9ec3a97d.jpg)

**Comment by dh13899396662** [comment]
下面是代码片段
if(data.success == 1) { //console.log(data)
  var content = document.getElementById(ids[lang]).getElementsByTagName("ul")[0];
  var expertData, rawSubnumber, subnumber, html = "",
  text = langsrc[langtext].tab.Subscribe;
  var myexpert = JSON.parse(localStorage.getItem('myexpert')); //alert(localStorage.getItem('myexpert'));
  var myexpertlist = [];
  for(var ii = 0, ilen = myexpert.length; ii < ilen; ii++) { //console.log('hahhhhahahha');
      //if(myexpert[ii].lang == 0) {
      myexpertlist.push(myexpert[ii].source);
      //}
    };
  var sub_flag = '';
  //console.log( '开始拼字符串' + (thtml = Date.now()) );
  for(var i = 0, len = data.dbres.length; i < len; i++) {
    sub_flag = '';
    expertData = data.dbres[i];
    rawSubnumber = expertData.subnumber;
    subnumber = stableFormat(rawSubnumber.toString()); //console.log(myexpertlist);
    if(myexpertlist.indexOf(expertData.source) !== -1) {
        sub_flag = 'delete ';
    };
    html = html +'<li data-subnumber="' + expertData.subnumber + '" data-lang="' + lang + '" class="mui-table-view-cell" data-title="' + expertData.title + '" data-image="' + expertData.image + '" data-src="' + expertData.source + '"><img class="e_img" data-src="' + expertData.source + '" src="https://app.tradeqq.cn/default/images/' + expertData.image + '" alt="">\
        <div class="titlebox">\
            <span class="e_title"  data-src="' + expertData.source + '">' + expertData.title + '</span>\
            <span class="e_title subtext"  data-subnumber="' + rawSubnumber + '">' + subnumber + '</span>\
        </div>\
        <span class="e_subscribe ' + sub_flag + expertData.source.replace(/\s+/g, "") + lang + '" data-src="' + expertData.source + '"></span>\
            </li>'
    };
    //console.log( '拼字符串用了   毫秒' + (Date.now() - thtml) );
    //console.log('这是语言' + lang);
    //content.style.display = 'none';
    content.innerHTML = html;

    if(reCount === 10) {
        setTimeout(afterLoadAll, 50)
        }
}

**Comment by dh13899396662** [comment]
代码如下：
![default](https://user-images.githubusercontent.com/32675044/33863165-741d0638-df21-11e7-8030-39f1bb10202d.png)

**Comment by dh13899396662** [comment]
代码如下，图像获取处为\<img>里的src路径
![default](https://user-images.githubusercontent.com/32675044/33863251-c7318614-df21-11e7-91aa-f16d0dc0eb8f.png)

**Comment by hbcui1984** [comment]
应该是safari的兼容问题，建议使用同样代码，直接在safari下运行测试。

**Comment by dh13899396662** [comment]
@hbcui1984 谢谢，这个问题已经解决了
原样是：ios浏览器对http协议要求严格，
这个https存在些问题，改为http就可以了
