### ISSUE TITLE
没有安装LeoShare模块是什么意思呢?

### ISSUE THREAD

**Issue by dh13899396662** [dcloudio/mui#384]
我在mainfest中没有找到LeoShare呀,求大神告知
<img width="533" alt="qq20171211-220817 2x" src="https://user-images.githubusercontent.com/32675044/33834990-f0f306c4-debf-11e7-9ad0-bc4a0c9f9021.png">
![f4c76644-9670-4fe7-9ce6-4d1f85ab8e82](https://user-images.githubusercontent.com/32675044/33835050-286db428-dec0-11e7-8804-4bd2207aac6a.JPG)
![img_1245](https://user-images.githubusercontent.com/32675044/33835058-32fab206-dec0-11e7-8eb0-f8619b38d68f.PNG)

**Comment by hbcui1984** [comment]
@nearwmy 跟进处理一下，应该是提示错误

**Comment by nearwmy** [comment]
你用的是什么版本的HBuilder 正式版还是Alpha版本，请贴出版本信息

**Comment by dh13899396662** [comment]
![default](https://user-images.githubusercontent.com/32675044/33868989-4f8c7086-df41-11e7-8765-f854436bf556.png)

**Comment by nearwmy** [comment]
此问题已确认为开发者自定义扩展的模块，需要开发者自己正确导入模块解决此问题
