### ISSUE TITLE
mui.pullToRefresh.js需要改下，setStopped并不会停止下拉事件

### ISSUE THREAD

**Issue by Joker1995** [dcloudio/mui#385]
改成这样就好了
setStopped: function(stopped) {
			if (stopped != this.stopped) {
				this.stopped = stopped;
				this.pullUpTips && this.pullUpTips.classList[stopped ? 'add' : 'remove'](CLASS_HIDDEN);
				if(stopped){
					this.element.removeEventListener('dragup', this);
					window.removeEventListener('scroll', this);
				}else{
					this.pullUpTipsIcon.innerHTML = this.options.up.contentdown;
					this.element.addEventListener('dragup', this);
					window.addEventListener('scroll', this);
					this.finished = false;
				}
			}
		}

**Comment by nearwmy** [comment]
此方法已经做了修复，可拉取最新版测试
