### ISSUE TITLE
动画怎么做性能高？

### ISSUE THREAD

**Issue by evenle** [dcloudio/mui#4]
用什么做动画性能搞点，用了JQ，在ipad效果很不理想啊！

**Comment by fonglezen** [comment]
不要用jq，直接用css3性能更好

**Comment by hbcui1984** [comment]
这个建议搜一搜css animation performance

**Comment by Thyiad** [comment]
最多用个zepto

**Comment by Thyiad** [comment]
而且css3的动画，在ios上很流畅的，如果你的动画ios都吃不消，那要是扔安卓上就得卡出翔了
