### ISSUE TITLE
mui有地图的控件吗？

### ISSUE THREAD

**Issue by zoii** [dcloudio/mui#40]
http://www.dcloud.io/helloh5/
这个体验APP中好像没有看到关于地图的展示。

**Comment by hbcui1984** [comment]
helloh5应用的Maps就是地图演示，对应规范参考：http://www.dcloud.io/docs/api/zh_cn/maps.shtml

这个和mui无关，你可参考如下文章了解mui和5+runtime的关系：http://ask.dcloud.net.cn/docs/#http://ask.dcloud.net.cn/article/91
