### ISSUE TITLE
demo中的列表到详情最佳实践请求有跨域问题

### ISSUE THREAD

**Issue by like-fly** [dcloudio/mui#442]
## 具体错误如下
Failed to load http://spider.dcloud.net.cn/api/news?column=id%2Cpost_id%2Ctitle%2Cauthor_name%2Ccover%2Cpublished_at: Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.
listview.html:1 Failed to load http://spider.dcloud.net.cn/api/banner/36kr?column=id%2Cpost_id%2Ctitle%2Cauthor_name%2Ccover%2Cpublished_at: Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by hbcui1984** [comment]
该示例仅支持在App中运行，浏览器下不支持。
若需要H5的示例，部署到自己的服务器，并修改域名地址即可。
