### ISSUE TITLE
这是什么情况？

### ISSUE THREAD

**Issue by Mesus** [dcloudio/mui#482]
![screenshot_20190612_102419](https://user-images.githubusercontent.com/18209480/59319474-6aec5b00-8cfd-11e9-8ba3-ed4933b60061.png)

**Comment by fxy060608** [comment]
http://ask.dcloud.net.cn/article/35998

**Comment by Mesus** [comment]
> http://ask.dcloud.net.cn/article/35998

明白了，感谢🙏
