### ISSUE TITLE
真搞笑，论坛上发了个报BUG的帖子，今天一看帖子被删了。66666

### ISSUE THREAD

**Issue by Axhale** [dcloudio/mui#489]

**Comment by laommmm** [comment]
根本没人管。

**Comment by 297179121** [comment]
你问的太多了 哈哈

**Comment by JackZhangfromChina** [comment]
解决不了问题,就解决问问题的人

**Comment by killkiss** [comment]
牛逼，这种态度。就应该放弃dcloud

**Comment by hbcui1984** [comment]
@Axhale 我们不会主动删除开发者帖子，但这几年只有几次例外，就是在论坛遭受恶意灌水的时候会批量删帖，此时可能会有误伤。

记得社区曾经一晚上被恶意发表数万帖子，当时运营将那一晚上的所有帖子全部隐藏了，你说的帖子消失，可能是这种情况牵连的。
