### ISSUE TITLE
为mui点赞

### ISSUE THREAD

**Issue by hbcui1984** [dcloudio/mui#49]
点赞步骤：
1、登录github；
2、找到mui项目，地址：https://github.com/dcloudio/mui ， 右上角分别点star和Fork；
3、进入mui点赞活动Issues，地址：https://github.com/dcloudio/mui/issues/49 ， 提交评论(comment)，评论内容为ask社区的用户名；
4、管理员看到Issues评论后，会尽快赠送积分

**Comment by XinHuaLuFang** [comment]
支持支持
askName:鑫花璐放
多送点，想参加那个抽奖活动，分不够了，哇咔咔~~~

**Comment by lemjean** [comment]
搞紧，中个肾6啊
用户名：jean      注册邮箱421112721@qq.com

**Comment by iwzh** [comment]
支持支持！
askname：温柔如斯
多送点！

**Comment by XinHuaLuFang** [comment]
lz赶紧跑，狼群来了

**Comment by letselfgo** [comment]
id letselfgo

给我加分吧

**Comment by udbmnm** [comment]
好项目不用说，刚出来时就已star
{askName : zkwap}

**Comment by luqipeng** [comment]
id 蛋炒饭   注册邮箱  376179174@qq.com
谢谢！！！

**Comment by misser92001** [comment]
用户名：感受呼吸
star
fork
return

**Comment by jianHuaRen2008** [comment]
用户名：飞上青天

**Comment by windtony** [comment]
我的用户名是wind

**Comment by baiyunchen** [comment]
DCloud Ask:
登录名：  baiyunchen@vip.qq.com
进去之后显示的那个名字：CloudBai  我不知道你们要哪个。。。

**Comment by hbcui1984** [comment]
@windtony 在ask上搜索wind，找不到你，你的注册邮箱是啥？
@lemjean  没看到你点star啊，赶紧的；

**Comment by jonas2015** [comment]
用户名 XG

**Comment by windtony** [comment]
我的注册邮箱是 windtony08@163.com

**Comment by tkggusraqk** [comment]
我很早就start了
我的问答账号是：576501565@qq.com

**Comment by enjoydegame** [comment]
start了，
帐号：34754319@qq.com
用户名：唐糖

**Comment by David1019** [comment]
askname: liangyue

**Comment by dingdingXL** [comment]
askname:野蛮人

**Comment by niten** [comment]
支持支持！
askname：南门看守者

**Comment by xiaohei445** [comment]
支持一下~askname:xiaohei445@qq.com

**Comment by jqz** [comment]
我的注册邮箱是：932316843@qq.com

**Comment by yuntianqing** [comment]
ask社区的用户名:杨羊羊 注册邮箱：yuntianqing2@163.com

**Comment by barbie19881023** [comment]
barbie_xw

**Comment by XinHuaLuFang** [comment]
又没中奖，再接再厉。。。呜呜~~~

**Comment by EEG5Black** [comment]
用户名：DasDan_

**Comment by caizeng** [comment]
用户名：pinkman

**Comment by jqz** [comment]
用户名：pinkman

**Comment by jqz** [comment]
用户名：jqz

**Comment by LAzyOnline** [comment]
很喜欢HBuilder 推荐给身边的朋友都说很棒
用户名:于是长大以后

**Comment by jqz** [comment]
很喜欢HBuilder ，支持。
用户名:jqz

**Comment by jwsblog** [comment]
用户名: jw
只关注如何抽奖

**Comment by icyflash** [comment]
用户名 icyflash
支持

**Comment by ljb202** [comment]
注册邮箱：ljb-202@126.com

**Comment by shiziwen** [comment]
已经fork并点赞。
邮箱：shiziwen@gmail.com

**Comment by KerwinChen** [comment]
askName:Kerwin。支持支持。

**Comment by shiziwen** [comment]
用户名:shiziwen
多谢。

**Comment by jwenlee** [comment]
支持支持
askName:jwenlee
jwen@vip.qq.com

**Comment by hotpoor-for-Liwei** [comment]
用户名：夏力维
顶~

**Comment by zzhsteady** [comment]
这里都是灌水的吗？

**Comment by evenle** [comment]
用户名：伟子 注册邮箱75407571@qq.com

**Comment by zhoujinliang** [comment]
亮亮 邮箱：zhoujinliang@gmail.com

**Comment by xiahuibing** [comment]
用户名：淡淡的冰 
邮箱：xiahuibing@qq.com

**Comment by yoShiSi** [comment]
加油
askname:多串君

**Comment by zhicheng99** [comment]
支持
用户名：qq123

**Comment by qiqi0** [comment]
注册邮箱：18500778881@163.com

**Comment by dingzhao** [comment]
支持，加油！ 
注册邮箱：332501337@qq.com

**Comment by shanxiangjohn** [comment]
注册邮箱：shanxiangjohn@gmail.com

**Comment by itnewmen** [comment]
支持miui itnewmen  注册邮箱 00102602@yto.net.cn

**Comment by zhoufan879** [comment]
用户名：Zhoufan879 
支持MUI，加油！

**Comment by arccos2002** [comment]
75027049@qq.com

**Comment by xwjonline** [comment]
肾6是我的了。用户名xwjonline
