### ISSUE TITLE
css普遍引用的这个资源已失效，影响加载速度。

### ISSUE THREAD

**Issue by wuxianlijiang** [dcloudio/mui#495]
几乎每个css都引用到了“https://cdn.dcloud.net.cn/img/mui-shadow-grey.png”，但该资源已失效，建议开发者更换资源url或移除该资源。

**Comment by changan12** [comment]
验证该图片资源有效

**Comment by babyNEKO** [comment]
可以访问，2020年5月10日12:08:15
