### ISSUE TITLE
想知道引入模板引擎的话对性能有多大影响？

### ISSUE THREAD

**Issue by scarletsky** [dcloudio/mui#53]
翻了一下文档，似乎 mui 并不支持模板继承。
不知道开发团队有没考虑过模板继承？
如果要引入模板引擎的话，不知道对性能有多大影响？

**Comment by udbmnm** [comment]
@scarletsky 模板引擎自己引入就行了，mui什么都做还能快吗？

**Comment by scarletsky** [comment]
@udbmnm 好~
