### ISSUE TITLE
下拉刷新在安卓下失效？

### ISSUE THREAD

**Issue by scarletsky** [dcloudio/mui#55]
分别用 iPhone5s、三儿子、Nexus 7 一代去测试官方例子中的 pullrefresh.html ，结果 iPhone5s 上/下拉刷新正常，三儿子和 N7 一代 上拉刷新正常，下拉刷新失效。

有解决办法吗？

**Comment by fxy060608** [comment]
你是在hello-mui里边测试？还是自己建的工程测试？android上的下拉刷新必须使用双webview模式

**Comment by scarletsky** [comment]
@fxy060608 
hello-mui 和 自己建的工程 都试过，安卓下都失效。
双 webview 模式具体怎么写？
我现在是按照文档里面的写法的：
```html
<!--下拉刷新容器-->
<div id="refreshContainer" class="mui-content mui-scroll-wrapper">
  <div class="mui-scroll">
    <!--数据列表-->
    <ul class="mui-table-view mui-table-view-chevron">
      
    </ul>
  </div>
</div>
```

**Comment by hbcui1984** [comment]
直接从http://dcloud.io/hellomui/下载hellomui，下拉刷新无法使用？
所谓双webview是两个页面的意思，参考：http://dcloudio.github.io/mui/javascript/#subpage

**Comment by fxy060608** [comment]
hello-mui里边跟pullrefresh.html对应的有一个template_pullrefresh.html，查看list.html里边这两个页面的组成代码，把pullrefresh页面append到template上

**Comment by scarletsky** [comment]
OK，我大概知道怎么做了~
