### ISSUE TITLE
子页面中如何获取父页面

### ISSUE THREAD

**Issue by uikoo9** [dcloudio/mui#58]
index.html中preload了几个页面list.html...
在这几个页面中都可以通过plus.webview.getWebviewById( id )的方法获取对应的页面，
例如plus.webview.getWebviewById('list')获取list.html页面，
但是如果要在list.html中获取index.html应该怎么写？

之前在本地使用plus.webview.getWebviewById('HBuilder')可以获取，但是打包之后就失效了，
也试过plus.webview.getWebviewById('index.html')照样不可以。

求助。

**Comment by uikoo9** [comment]
主页面对应的id是manifest.json中的appid

**Comment by fxy060608** [comment]
最好不要写死，应该使用plus.webview.getWebviewById(plus.runtime.appid);来获取首页，
这样可以保证真机联调，云打包都可以正常运行

**Comment by uikoo9** [comment]
多谢，建议可以把这个也封装为一个方法，类似plus.webview.indexPage这样。

**Comment by hbcui1984** [comment]
下一版本将会新增plus.webview.getLaunchWebview()方法获取应用的入口WebviewObject窗口对象；
