### ISSUE TITLE
找不到文档！

### ISSUE THREAD

**Issue by wss1942** [dcloudio/mui#69]

**Comment by wss1942** [comment]
文档太烂了，这他妈的也叫文档，很多东西都找不到，参数也不给。能不能弄个传统点的文档，chm之类的，玩什么新奇，文档这么烂你那东西再好用不起来有个屁用！

**Comment by xd199153** [comment]
请参考  HelloMui. 不要把无知当个性

**Comment by wss1942** [comment]
@xd199153 我说文档不好你还不爱听，我看android的文档怎么没感觉不好，看百度的文档怎么没感觉不好。别会点东西了就感觉自己牛逼啦，装什么13，你tm的没无知过吗？我就无知我才看文档，我要是啥都知道还看个屁。

**Comment by xd199153** [comment]
@wss1942  不撕逼,已删.
