### ISSUE TITLE
mui可以做微信应用开发不呢

### ISSUE THREAD

**Issue by tangjiale** [dcloudio/mui#86]

**Comment by dancinglone** [comment]
不涉及h5+的部分就可以咯

**Comment by osReilly** [comment]
需要自己去分离哪些h5+部分

**Comment by hbcui1984** [comment]
可以的，建议参考[mui适用场景说明，能不能在普通浏览器里使用，能否用于wap网站](http://ask.dcloud.net.cn/docs/#http://ask.dcloud.net.cn/article/113)；

已有不少网友使用mui开发了微信项目，比如[天行者户外](http://m.skywalk-er.com/)

**Comment by limeng0403** [comment]
还是考虑更专业更稳定的框架吧，得考虑用户流量问题，框架太大，用户会骂街的。

**Comment by hbcui1984** [comment]
mui支持微信App开发，微信直接访问：http://www.dcloud.io/hellomui 就可以体验；或者微信扫描如下二维码：[微信扫码](http://dcloud.io/hellomui/images/code.png =120x120)
